version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ktlint-lib includes multiple (old) versions of logger and standard ruleset so that the user can choose which version of ktlint
      # rules are used. Those versions should never be bumped.
      - dependency-name: "com.pinterest.ktlint:ktlint-logger"
        update-types: [ version-update:semver-major , version-update:semver-minor,  version-update:semver-patch]
      - dependency-name: "com.pinterest.ktlint:ktlint-ruleset-standard"
        update-types: [ version-update:semver-major , version-update:semver-minor,  version-update:semver-patch]
