name: Free Disk Space

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      run: |
        echo "Disk space before cleanup:"
        df -h

      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false

      # https://github.com/actions/runner-images/issues/10386#issuecomment-2271613335
      - name: Free Disk Space
        run: |
          echo "Disk space before cleanup:"
          df -h
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android/sdk/ndk
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt-get clean
          echo "Disk space after cleanup:"
          df -h
