# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Release
on:
  release:
    types: [prereleased, released]

jobs:

  # Prepare and publish the plugin to the Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    steps:
      # Indicate start of publish to Rollbar
      - name: Notify start deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.2
        id: rollbar_pre_deploy
        with:
          environment: 'production'
          version: ${{ github.event.release.tag_name }}
          status: 'started'
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ACTIONS_ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Builds secrets file
      - name: Build secrets file
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        shell: bash
        run: echo "ROLLBAR_ACCESS_TOKEN=$ROLLBAR_ACCESS_TOKEN" >> secrets.properties

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin

      # Indicate success of publish to Rollbar
      - name: Notify finish deploy to Rollbar
        uses: rollbar/github-deploy-action@2.1.2
        id: rollbar_post_deploy
        with:
          environment: 'production'
          version: ${{ github.event.release.tag_name }}
          status: 'succeeded'
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ACTIONS_ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}
          DEPLOY_ID: ${{ steps.rollbar_pre_deploy.outputs.deploy_id }}

  # Patch changelog, commit and push to the current repository
  changelog:
    name: Update Changelog
    needs: release
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Builds secrets file
      - name: Build secrets file
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
        shell: bash
        run: echo "ROLLBAR_ACCESS_TOKEN=$ROLLBAR_ACCESS_TOKEN" >> secrets.properties

      # Update Unreleased section with the current version
      - name: Patch Changelog
        run: ./gradlew patchChangelog

      # Commit patched Changelog
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update changelog" -a

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
